"""add_more_assessment_info

Revision ID: 0966d42483b3
Revises: 6628cf6ea000
Create Date: 2026-07-14 20:41:57.857489

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0966d42483b3"
down_revision: str | Sequence[str] | None = "6628cf6ea000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assessments", sa.Column("summary", sa.Text(), nullable=False))
    op.add_column("assessments", sa.Column("summary_positives", sa.Text(), nullable=False))
    op.add_column("assessments", sa.Column("summary_negatives", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "summary_negatives")
    op.drop_column("assessments", "summary_positives")
    op.drop_column("assessments", "summary")
    # ### end Alembic commands ###
