"""add_linkedin_slug_to_company_details

Revision ID: 289481da817e
Revises: 41bfa88e89b6
Create Date: 2026-07-14 17:38:12.398366

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "289481da817e"
down_revision: str | Sequence[str] | None = "41bfa88e89b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company_details", sa.Column("linkedin_slug", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "company_details", ["linkedin_slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("company_details_linkedin_slug_key", "company_details", type_="unique")
    op.drop_column("company_details", "linkedin_slug")
    # ### end Alembic commands ###
