"""drop_company_name_unique

Revision ID: 296bab0d47be
Revises: d7ae67786212
Create Date: 2026-07-19 14:56:49.337036

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "296bab0d47be"
down_revision: str | Sequence[str] | None = "d7ae67786212"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("company_details_name_key"), "company_details", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("company_details_name_key"),
        "company_details",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
