"""make_columns_notnull

Revision ID: 6628cf6ea000
Revises: 0716795b7fd1
Create Date: 2026-07-14 18:37:23.126995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6628cf6ea000"
down_revision: str | Sequence[str] | None = "0716795b7fd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("jobs", "search_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("user_searches", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_searches", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("jobs", "search_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
