"""add_linkedin_slug_to_company_details

Revision ID: 97f6c0b8c574
Revises: 41bfa88e89b6
Create Date: 2026-07-14 17:24:26.437376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97f6c0b8c574"
down_revision: str | Sequence[str] | None = "41bfa88e89b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company_details", sa.Column("linkedin_slug", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "uq_company_details_linkedin_slug", "company_details", ["linkedin_slug"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_company_details_linkedin_slug", "company_details", type_="unique")
    op.drop_column("company_details", "linkedin_slug")
    # ### end Alembic commands ###
