"""move_criteria_to_users

The criteria text moves out of the "criteria_text" settings row onto the first
user (a "Default" user is created to carry it if none exists). Nothing else
uses settings, so the table is dropped.

Revision ID: f46b5aaae86e
Revises: 5ce6aa568eb3
Create Date: 2026-07-14 12:44:42.254289

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f46b5aaae86e"
down_revision: str | Sequence[str] | None = "5ce6aa568eb3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

settings = sa.table(
    "settings",
    sa.column("key", sa.Text),
    sa.column("value", sa.Text),
    sa.column("updated_at", sa.DateTime(timezone=True)),
)

users = sa.table(
    "users",
    sa.column("id", sa.Integer),
    sa.column("name", sa.Text),
    sa.column("criteria_text", sa.Text),
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    row = bind.execute(sa.select(settings.c.value).where(settings.c.key == "criteria_text")).first()
    if row:
        first_user_id = bind.execute(sa.select(users.c.id).order_by(users.c.id).limit(1)).scalar()
        if first_user_id is None:
            bind.execute(users.insert().values(name="Default", criteria_text=row.value))
        else:
            bind.execute(
                users.update().where(users.c.id == first_user_id).values(criteria_text=row.value)
            )
    op.drop_table("settings")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("settings_pkey")),
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    criteria = bind.execute(
        sa.select(users.c.criteria_text).order_by(users.c.id).limit(1)
    ).scalar()
    if criteria:
        bind.execute(
            settings.insert().values(key="criteria_text", value=criteria, updated_at=sa.func.now())
        )
