"""soft_delete_user_search

Revision ID: f75ac168dbd0
Revises: 0966d42483b3
Create Date: 2026-07-18 13:24:23.633162

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f75ac168dbd0"
down_revision: str | Sequence[str] | None = "0966d42483b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_searches", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_searches", "deleted_at")
    # ### end Alembic commands ###
